2019-04-06 15:58:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE REORDER VALUES[*](REORDER_ID VARCHAR(255), VENDOR_ID VARCHAR(255), UPC VARCHAR(255), AMOUNT VARCHAR(255), SHIPMENT VARCHAR(255), DELIVERY_DATE VARCHAR(255), STORE_ID VARCHAR(255)) "; SQL statement:
create table reorder values(reorder_id varchar(255), vendor_id varchar(255), UPC varchar(255), amount varchar(255), shipment varchar(255), delivery_date varchar(255), store_id varchar(255)) [42000-199]
2019-04-06 16:00:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-06 16:04:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-06 16:28:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-06 16:28:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-06 16:50:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:36:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:36:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:39:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:39:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:40:22 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at Applications.MethodCalls.createConnection(MethodCalls.java:24)
	at Applications.OnlineApplication.main(OnlineApplication.java:28)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2019-04-08 12:40:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:40:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:41:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:42:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:44:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:45:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:46:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-08 12:47:01 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at Applications.AdminApplication.createConnection(AdminApplication.java:23)
	at Applications.AdminApplication.main(AdminApplication.java:88)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2019-04-08 12:50:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT FROM CONTAINS WHERE[*] UPC='036515110187' AND STORE_ID='5' "; expected "., (, USE, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select from contains where upc='036515110187' and store_id='5' [42001-199]
2019-04-08 12:50:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT FROM CONTAINS WHERE[*] UPC='036515110187' AND STORE_ID='5' "; expected "., (, USE, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select from contains where UPC='036515110187' and store_id='5' [42001-199]
2019-04-08 22:56:47 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at Applications.MethodCalls.createConnection(MethodCalls.java:25)
	at Applications.OnlineApplication.main(OnlineApplication.java:28)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2019-04-08 22:57:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "CUST_ID" not found; SQL statement:
Select * from customer where cust_id='9' [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:205)
	at org.h2.command.dml.Select.prepare(Select.java:1248)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:78)
	at Applications.MethodCalls.putOrder(MethodCalls.java:291)
	at Applications.OnlineApplication.main(OnlineApplication.java:235)
2019-04-08 23:00:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "CUST_ID" not found; SQL statement:
Select * from customer where cust_id='9' [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.expression.condition.Comparison.optimize(Comparison.java:205)
	at org.h2.command.dml.Select.prepare(Select.java:1248)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:78)
	at Applications.MethodCalls.putOrder(MethodCalls.java:288)
	at Applications.OnlineApplication.main(OnlineApplication.java:235)
2019-04-08 23:48:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ORDER_ID" not found; SQL statement:
WITH try1 as (SELECT order_id FROM contains JOIN Product ON Product.UPC = contains.UPC), select order_id from try1 JOIN orders ON contains.order_id = orders.order_id [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Select.prepare(Select.java:1245)
	at org.h2.table.TableView.createQueryColumnTemplateList(TableView.java:789)
	at org.h2.command.Parser.parseSingleCommonTableExpression(Parser.java:6428)
	at org.h2.command.Parser.parseWith1(Parser.java:6299)
	at org.h2.command.Parser.parseWith(Parser.java:6284)
	at org.h2.command.Parser.parseWithStatementOrQuery(Parser.java:2453)
	at org.h2.command.Parser.parsePrepared(Parser.java:818)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:78)
	at Applications.MethodCalls.viewOrders(MethodCalls.java:337)
	at Applications.OnlineApplication.main(OnlineApplication.java:75)
2019-04-08 23:49:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PRODUCTS" not found; SQL statement:
WITH try1 as (SELECT order_id FROM contains,products), select order_id from try1 JOIN orders ON contains.order_id = orders.order_id [42102-199]
2019-04-08 23:50:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ORDER_ID" not found; SQL statement:
WITH try1 as (SELECT order_id FROM contains,product), select order_id from try1 JOIN orders ON contains.order_id = orders.order_id [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Select.prepare(Select.java:1245)
	at org.h2.table.TableView.createQueryColumnTemplateList(TableView.java:789)
	at org.h2.command.Parser.parseSingleCommonTableExpression(Parser.java:6428)
	at org.h2.command.Parser.parseWith1(Parser.java:6299)
	at org.h2.command.Parser.parseWith(Parser.java:6284)
	at org.h2.command.Parser.parseWithStatementOrQuery(Parser.java:2453)
	at org.h2.command.Parser.parsePrepared(Parser.java:818)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:78)
	at Applications.MethodCalls.viewOrders(MethodCalls.java:337)
	at Applications.OnlineApplication.main(OnlineApplication.java:75)
2019-04-08 23:50:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ORDER_ID" not found; SQL statement:
WITH try1 as (SELECT order_id FROM contains,product), 
                    select order_id from try1 JOIN orders ON contains.order_id = orders.order_id [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Select.prepare(Select.java:1245)
	at org.h2.table.TableView.createQueryColumnTemplateList(TableView.java:789)
	at org.h2.command.Parser.parseSingleCommonTableExpression(Parser.java:6428)
	at org.h2.command.Parser.parseWith1(Parser.java:6299)
	at org.h2.command.Parser.parseWith(Parser.java:6284)
	at org.h2.command.Parser.parseWithStatementOrQuery(Parser.java:2453)
	at org.h2.command.Parser.parsePrepared(Parser.java:818)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
2019-04-08 23:50:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ORDER_ID" not found; SQL statement:
WITH try1 as (SELECT order_id FROM contains,product), 
                    select order_id from try1 [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Select.prepare(Select.java:1245)
	at org.h2.table.TableView.createQueryColumnTemplateList(TableView.java:789)
	at org.h2.command.Parser.parseSingleCommonTableExpression(Parser.java:6428)
	at org.h2.command.Parser.parseWith1(Parser.java:6299)
	at org.h2.command.Parser.parseWith(Parser.java:6284)
	at org.h2.command.Parser.parseWithStatementOrQuery(Parser.java:2453)
	at org.h2.command.Parser.parsePrepared(Parser.java:818)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
2019-04-08 23:51:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ORDER_ID" not found; SQL statement:
WITH try1 as (SELECT order_id FROM contains,product) [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Select.prepare(Select.java:1245)
	at org.h2.table.TableView.createQueryColumnTemplateList(TableView.java:789)
	at org.h2.command.Parser.parseSingleCommonTableExpression(Parser.java:6428)
	at org.h2.command.Parser.parseWith1(Parser.java:6299)
	at org.h2.command.Parser.parseWith(Parser.java:6284)
	at org.h2.command.Parser.parseWithStatementOrQuery(Parser.java:2453)
	at org.h2.command.Parser.parsePrepared(Parser.java:818)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
2019-04-08 23:51:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "ORDER_ID" not found; SQL statement:
WITH try1 as (SELECT order_id FROM order_id,product) [42102-199]
2019-04-08 23:51:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "WITH statement supports only SELECT, TABLE, VALUES, CREATE TABLE, INSERT, UPDATE, MERGE or DELETE statements"; SQL statement:
WITH try1 as (SELECT order_id FROM orders,product) [42000-199]
2019-04-08 23:51:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "WITH TRY1 AS (SELECT ORDER_ID FROM ORDERS,PRODUCT), SELECT[*] * FROM TRY1 "; expected "identifier"; SQL statement:
WITH try1 as (SELECT order_id FROM orders,product), select * from try1 [42001-199]
2019-04-08 23:52:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "WITH statement supports only SELECT, TABLE, VALUES, CREATE TABLE, INSERT, UPDATE, MERGE or DELETE statements"; SQL statement:
WITH try1 as (SELECT order_id FROM orders,product) [42000-199]
2019-04-08 23:52:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TRY1" not found; SQL statement:
select * from try1 [42102-199]
2019-04-08 23:52:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "WITH statement supports only SELECT, TABLE, VALUES, CREATE TABLE, INSERT, UPDATE, MERGE or DELETE statements"; SQL statement:
WITH try1 as (SELECT order_id FROM orders) [42000-199]
2019-04-08 23:52:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TRY1" not found; SQL statement:
select * from try1 [42102-199]
2019-04-08 23:53:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "WITH A1(ID)AS
    (SELECT ORDER_ID
    FROM ORDERS),
    SELECT[*] ID
    FROM A1 "; expected "identifier"; SQL statement:
WITH a1(id)as
    (SELECT order_id
    FROM orders),
    SELECT id
    FROM a1 [42001-199]
2019-04-08 23:53:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "WITH A1(ID)AS
    (SELECT ORDER_ID
    FROM ORDERS),
    SELECT[*] ID
    FROM A1 "; expected "identifier"; SQL statement:
WITH a1(id)as
    (SELECT order_id
    FROM orders),
    SELECT id
    FROM a1 [42001-199]
2019-04-08 23:53:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Function "ORDERS" not found; SQL statement:
WITH a1(id) as
    (SELECT order_id
    FROM orders(order_id),
    SELECT id
    FROM a1 [90022-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.readJavaFunction(Parser.java:3288)
	at org.h2.command.Parser.readFunction(Parser.java:3495)
	at org.h2.command.Parser.readTableFunction(Parser.java:1937)
	at org.h2.command.Parser.readTableFilter(Parser.java:1892)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2641)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2788)
	at org.h2.command.Parser.parseSelectSub(Parser.java:2636)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:2469)
	at org.h2.command.Parser.parseSelect(Parser.java:2440)
	at org.h2.command.Parser.parseSingleCommonTableExpression(Parser.java:6423)
	at org.h2.command.Parser.parseWith1(Parser.java:6299)
	at org.h2.command.Parser.parseWith(Parser.java:6284)
	at org.h2.command.Parser.parseWithStatementOrQuery(Parser.java:2453)
	at org.h2.command.Parser.parsePrepared(Parser.java:818)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
2019-04-08 23:55:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "WITH TEMPORARYTABLE (AVERAGEVALUE) AS
    (SELECT ORDER_ID
    FROM ORDERS),
    SELECT[*] ORDER_ID
    FROM TEMPORARYTABLE "; expected "identifier"; SQL statement:
WITH temporaryTable (averageValue) as
    (SELECT order_id
    FROM orders),
    SELECT order_id
    FROM temporaryTable [42001-199]
2019-04-09 13:32:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Ambiguous column name "ORDER_ID"; SQL statement:
select order_id, upc from includes join orders on includes.order_id=orders.order_id [90059-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:142)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:116)
	at org.h2.command.dml.Select.mapColumns(Select.java:1629)
	at org.h2.command.dml.Select.init(Select.java:1164)
	at org.h2.command.Parser.parseSelect(Parser.java:2447)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
2019-04-09 13:33:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Ambiguous column name "ORDER_ID"; SQL statement:
select order_id, upc from includes join orders [90059-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:142)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:116)
	at org.h2.command.dml.Select.mapColumns(Select.java:1629)
	at org.h2.command.dml.Select.init(Select.java:1164)
	at org.h2.command.Parser.parseSelect(Parser.java:2447)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
2019-04-09 13:33:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Ambiguous column name "ORDER_ID"; SQL statement:
select order_id from includes join orders [90059-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:142)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:116)
	at org.h2.command.dml.Select.mapColumns(Select.java:1629)
	at org.h2.command.dml.Select.init(Select.java:1164)
	at org.h2.command.Parser.parseSelect(Parser.java:2447)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
2019-04-09 13:34:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Ambiguous column name "ORDER_ID"; SQL statement:
SELECT order_id
FROM Orders
JOIN includes [90059-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:142)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:116)
	at org.h2.command.dml.Select.mapColumns(Select.java:1629)
	at org.h2.command.dml.Select.init(Select.java:1164)
	at org.h2.command.Parser.parseSelect(Parser.java:2447)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
2019-04-09 13:38:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Ambiguous column name "ORDER_ID"; SQL statement:
SELECT order_id, upc
FROM Orders join includes where customer_id ='9' [90059-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:142)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:116)
	at org.h2.command.dml.Select.mapColumns(Select.java:1629)
	at org.h2.command.dml.Select.init(Select.java:1164)
	at org.h2.command.Parser.parseSelect(Parser.java:2447)
	at org.h2.command.Parser.parsePrepared(Parser.java:814)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
2019-04-09 17:29:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CUSTOMER" not found; SQL statement:
drop table customer [42102-199]
2019-04-09 17:29:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE CUSTOMER(
CUSTOMER_ID VARCHAR(255) PRIMARY KEY,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
NUM VARCHAR(255),
STREET VARCHAR(255),
CITY VARCHAR(255),
STATE VARCHAR(255),
ZIP VARCHAR(255),
EMAIL VARCHAR(255),
PASSWORD VARCHAR(255)
CREDIT[*] VARCHAR(255)); "; expected "FOR, UNSIGNED, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
Create table customer(
customer_id varchar(255) primary key,
first_name varchar(255),
last_name varchar(255),
num varchar(255),
street varchar(255),
city varchar(255),
state varchar(255),
zip varchar(255),
email varchar(255),
password varchar(255)
credit varchar(255)); [42001-199]
2019-04-09 17:29:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CUSTOMER" not found; SQL statement:
INSERT INTO customer (customer_id, first_name, last_name, num, street, city, state, zip, email, password, credit) VALUES('1','Bryan','Passino','20','Long Memorial Drive','Rochester','NY','14623','bjpvcs@rit.edu','bp','0'),('2','Joy','Notjoy','30','Memorial Drive','Avon','MA','2322','pxj@rit.edu','jn','0'),('3','James','Oh','250','Hartford Avenue','Bellingham','MA','2019','jameskim@gmail.com','jo','0'),('4','Jack','Oh','700','Oak Street','Brockton','MA','2301','jackkim@gmail.com','jo2','0'),('5','Sarah','Banana','66','Parkhurst Rd','Chelmsford','MA','1824','fruitmeup@gmail.com','sb','0'),('6','Bob','Marley','591','Memorial Dr','Chicopee','MA','1020','guitarsenpai@hotmail.com','bm','0'),('7','Ryan','Brother','137','Teaticket Hwy','East Falmouth','MA','2536','artesano7718@gmail.com','rb','0'),('8','Monica','Geller','42','Fairhaven Commons Way','Fairhaven','MA','2719','cleanfreak221@friends.edu','mg','0'),('9','Abhaya','Tamrakar','374','William S Canning Blvd','Fall River','MA','2721','abhaya.tmkr@gmail.com','at','0'),('10','Joey','Tribianni','121','Worcester Rd','Framingham','MA','1701','daysofourlives3@friends.com','jt','0'),('11','Ross','Geller','677','Timpany Blvd','Gardner','MA','1440','dinasourisbae@friends.com','rg','0'),('12','Rachel','Green','337','Russell St','Hadley','MA','1035','fashinismypassion@friends.com','rg2','0'),('13','Phoebe','Buffay','295','Plymouth Street','Halifax','MA','2338','weirdismyjam@friends.com','pb','0'),('14','Carol','Reed','1775','Washington St','Hanover','MA','2339','tigersuite@rit.edu','cr','0'),('15','Chandler','Bing','280','Washington Street','Hudson','MA','1749','funnyismything@friends.com','cb','0'),('16','RIchard','Bruke','20','Soojian Dr','Leicester','MA','1524','imanotold@friends.com','rb','0'),('17','Gunter','Watson','11','Jungle Road','Leominster','MA','1453','coffeeeisgoodcoffee@gmail.com','gw','0'),('18','Trevor ','Noah','301','Massachusetts Ave','Lunenburg','MA','1462','icametorit@rit.edu','tn','0'),('19','Donald','Trump','780','Lynnway','Lynn','MA','1905','endingsoon@hotmail.com','dt','0'),('20','Hugh','Jackman','55','Brooksby Village Way','Danvers','MA','1923','wolverine99@marvel.com','hj','0'); [42102-199]
2019-04-09 17:36:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CUSTOMER(CREDIT) VALUES('3.49') WHERE[*] CUSTOMER_ID = '9'; "; SQL statement:
Insert into customer(credit) values('3.49') where customer_id = '9'; [42000-199]
2019-04-09 17:37:26 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:299)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:782)
	at org.h2.server.web.WebApp.login(WebApp.java:1004)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 30 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 24 more
2019-04-09 17:37:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO CUSTOMER(CREDIT) VALUES('3.49') WHERE[*] CUSTOMER_ID = '9' "; SQL statement:
Insert into customer(credit) values('3.49') where customer_id = '9' [42000-199]
2019-04-09 17:42:49 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at Applications.MethodCalls.createConnection(MethodCalls.java:26)
	at Applications.OnlineApplication.main(OnlineApplication.java:27)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2019-04-09 17:50:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-09 17:53:29 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at Applications.MethodCalls.createConnection(MethodCalls.java:26)
	at Applications.OnlineApplication.main(OnlineApplication.java:27)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2019-04-09 17:54:49 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at Applications.MethodCalls.createConnection(MethodCalls.java:26)
	at Applications.OnlineApplication.main(OnlineApplication.java:27)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 26 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/abhay/IdeaProjects/Retail_Database/retailDb/retailDb.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 20 more
2019-04-09 18:13:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-09 18:15:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
2019-04-09 18:15:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: No data is available [2000-199]
